apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: testcluster
  region: us-east-1

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    
vpc:
  subnets:
    private:
      us-east-1a:
        id: subnet-0375cdbc08f810c72
      us-east-1b:
        id: subnet-04f0a41697f94a460
    public:
      us-east-1a:
        id: subnet-0fca6bb03c01116ed
      us-east-1b:
        id: subnet-0bb86aac6bac9af6b

iam:
  withOIDC: true

managedNodeGroups:
- desiredcapacity: 3
  instanceType: t3a.medium
  maxSize: 3
  minSize: 1
  name: nodegrp1
  volumesize: 20
  ssh:
    allow: true
    publicKeyName: guacamole-test